export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const ADD_ABOUT = 'ADD_ABOUT';
export const ADD_ABOUTS = 'ADD_ABOUTS';
export const ADD_EVENT = 'ADD_EVENT';
export const ADD_EVENTS = 'ADD_EVENTS';
export const ADD_IDEA = 'ADD_IDEA';
export const ADD_IDEAS= 'ADD_IDEAS';
export const DELETE_IDEA= 'DELETE_IDEA';
